project:
  type: website
  output-dir: docs

website:
  site-url: https://mclab-plant-pathology.co.za
  title: "McLab Field Pathology & Epidemiology Group"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Who We Are
      - href: team.qmd
        text: Meet the Team
      - href: projects.qmd
        text: Projects
      - href: updates.qmd
        text: What We Are Up To
      - href: acknowledgments.qmd
        text: Acknowledgments
      - href: contact.qmd
        text: Contact & Work With Us

format:
  html:
    theme:
      light: lux
      dark: darkly
    scss: styles.scss


resources:
  - CNAME
  - images
