project:
  type: website
  output-dir: docs

website:
  title: "McLab Field Pathology & Epidemiology Group"
  site-url: "https://mclab-plant-pathology.co.za"
  favicon: images/logo.png

  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Background & Vision
      - href: team.qmd
        text: Meet the Team
      - href: projects.qmd
        text: Projects
      - href: acknowledgments.qmd
        text: Acknowledgments
      - href: updates.qmd
        text: What we are up to
      - href: contact.qmd
        text: Contact & Work with us

  page-footer:
    center: "Â© 2025 McLab Field Pathology & Epidemiology Group"

format:
  html:
    theme:
      - cosmo
    css:
      - styles.scss
    toc: false
    smooth-scroll: true
    link-external-newwindow: true

execute:
  echo: false
  warning: false
  message: false
